### ISSUE TITLE
Add a authenticator

### ISSUE THREAD

**Issue by ullgren** [bankid4keycloak/bankid4keycloak#10]
Add a Authenticator to allow for adding BankID validation in a authentication flow. Possible use case would be to allow for using BankID as a form of MFA or to allow adding certain roles when BankID is used as part of the authentication flow.

**Comment by qvicksilver** [comment]
Did we decide to close this one because of the "Identity Provider Redirector" action or were there any other issues?

**Comment by ullgren** [comment]
Yes that was the decision.
