### ISSUE TITLE
Support for Keycloak 10.x

### ISSUE THREAD

**Issue by rickardpl** [bankid4keycloak/bankid4keycloak#13]
Using Keycloak-10.0.2. Deployed and configured bankid identityprovider as instructed using key/truststore from existing working bankid application. 

Run into this whatever I do, problem manifests itself before getting into debuggable code. Tried to set media type, but that should be done by freemarker implementation.

17:39:23,804 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (default task-2) MediaType not set on path /auth/realms/mytestrealm/broker/bankid/login, with response status 307
17:39:23,808 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error

Disclaimer! Is totally new to keycloak so UBD may have occurred.

**Comment by niot29** [comment]
I have exactly the same problem. run the same version of Keycloak-10.0.2.

**Comment by ullgren** [comment]
Thanks for the report.
We have only tested the project with Keycloak 9.x (9.0.2 to be exact).

Some initial tests shows that there are some issues with keycloak 10.x. I will rename this issue to be "Support for Keycloak 10.x".

**Comment by isrjo** [comment]
Quite certain this is due to --> https://github.com/keycloak/keycloak/pull/7079
As you see a fix was merged a few days ago, whereas i'm pretty sure this issue will self repair.
If you're not dependent upon 10.x I'd suggest we skip that version entirely and jump straight to 11 (master is now tagged 11.0), that includes this fix.

I've created a docker image from master including this fix as well as our bankid broker.
You're more than welcome to try it out, please not however I've only tested it for a few minutes, but for evaluation and or testing it should do the trick. 

It's basically just a wrapper around the official keycloak container -> https://hub.docker.com/r/jboss/keycloak/

An example on howto start it. Please note the volume path needs adjustents.
  ```docker run -d --name keycloak -v /home/isrjo/tmp/tls:/tls -p8080:8080 -e "KEYCLOAK_USER=admin" -e KEYCLOAK_PASSWORD="supersecret" bankid4keycloak/bankid4keycloak:1```

**Comment by danold** [comment]
Does the performLogin method in [BankidIdentityProvider](https://github.com/bankid4keycloak/bankid4keycloak/raw/master/src/main/java/org/keycloak/broker/bankid/BankidIdentityProvider.java) really need to use temporary redirect(307)?

Changing this to a 302 or 303 is sufficient to avoid the MediaType problem in Keyclaok 10.0.2, although I agree that 307 should be supported by Keycloak.

**Comment by rickardpl** [comment]
Did a local change and changed to ResponseseeOther and this works in 10.0.2
	```
@Override
	public Response performLogin(AuthenticationRequest request) {
		try {
			return Response.seeOther
```

**Comment by danold** [comment]
> Did a local change and changed to Response.seeOther (because this was the only other redirect method) and this works in 10.0.2
> 
> ```
> @Override
> 	public Response performLogin(AuthenticationRequest request) {
> 		try {
> 			return Response.seeOther
> ```

Any redirect status is possible using
`Response.status(302).location(`
The seeOnly and temporaryRedirect are only convenience methods for the above. Not sure though which status would be the most "correct" one to use if that even matters.

**Comment by ullgren** [comment]
Thanks for the investigation and proposed solution. If anyone of you want to create a pull request you are welcome. Otherwise I will implement this next time I have time to work on the project. Probably sometime this weekend.

**Comment by ullgren** [comment]
Thanks for the investigation and proposed solution. If anyone of you want to create a pull request you are welcome. Otherwise I will implement this next time I have time to work on the project. Probably sometime this weekend.
