### ISSUE TITLE
Charset problem in keycloak user form for initial user creation in keycloak

### ISSUE THREAD

**Issue by rickardpl** [bankid4keycloak/bankid4keycloak#14]
First identification will show a user form with first/last name showing utf-8 character sequence for swedish characters åäö.
![bankid4keycloak_utf8_err](https://user-images.githubusercontent.com/16462691/85543336-428a8280-b61a-11ea-9a8a-5392110269fa.jpg)

**Comment by rickardpl** [comment]
Problem is already manifesting itself in the rest response from bankid. After adding a lot of log.debug I can see this returned in SimpleBankidClient.sendCollect()
name=S├╢lve Dahlstr├╢m, givenName=S├╢lve, surname=Dahlstr├╢m

I am running the keycloak server on windoze and that implicitly means iso1252 aka cp850 charset. 

I don't know how keycloak SimpleHttp works but it is using the wrong charset for jackson.

**Comment by ullgren** [comment]
I do not hava a windows machine to use for reproducing this right now. However could you please try adding  ` -Dfile.encoding=UTF-8` to `JAVA_OPTS` in `standalone.conf`and see if this solved the problem.

The complete line should be something like this.

```
#
# Specify options to pass to the Java VM.
#
if [ "x$JAVA_OPTS" = "x" ]; then
   JAVA_OPTS="-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true"
   JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS -Djava.awt.headless=true"
else
   echo "JAVA_OPTS already set in environment; overriding default settings with values: $JAVA_OPTS"
fi

# Add this line 
JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8
```

**Comment by rickardpl** [comment]
Nope, does not solve the problem :

```
> 14:10:29,600 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: Keycloak 9.0.3 (WildFly Core 10.0.3.Final) starting
> 14:10:29,601 DEBUG [org.jboss.as.config] (MSC service thread 1-2) Configured system properties:
>         awt.toolkit = sun.awt.windows.WToolkit
```

From the debugger
![bild](https://user-images.githubusercontent.com/16462691/85717864-3c65d600-b6ee-11ea-9a30-8f6e5fbf9cd9.png)

**Comment by ullgren** [comment]
Hi,

Sorry I gave you the wrong instructions, since you are on Windows the change should go into `standalone.conf.bat` provided you start keycloak using the `standalone.bat` script.

Find the rows where the JAVA_OPTS are set and add -Dfile.encoding=UTF-8

```

rem # JVM memory allocation pool parameters - modify as appropriate.
set "JAVA_OPTS=-Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"

rem # Prefer IPv4
set "JAVA_OPTS=%JAVA_OPTS% -Djava.net.preferIPv4Stack=true"

rem # Make Byteman classes visible in all module loaders
rem # This is necessary to inject Byteman rules into AS7 deployments
set "JAVA_OPTS=%JAVA_OPTS% -Djboss.modules.system.pkgs=org.jboss.byteman"

rem # Add this to solve character encoding problems
set "JAVA_OPTS=%JAVA_OPTS% -Dfile.encoding=UTF-8"
```

**Comment by ullgren** [comment]
@isrjo We should add this to the README.md installation notes.

**Comment by rickardpl** [comment]
Changing this is not the way to go since it will affect the whole operation for all filehandling in the server.

Without knowing all the methods of SimpleHttpClient I do know that when jacson has control over the returned inputstream it will handle the respone correctly.

**Comment by ullgren** [comment]
Well I would argue that using UTF-8 as `file.encoding` is preferred when running Java applications. But I agree for a already running keycloak instance this could potentially be a problem.

Looking a bit deeper into the problem it looks like you are correct the assumption that it is the SimpleHttp library that is part of the  problem. 
https://github.com/keycloak/keycloak/blob/9.0.3/server-spi-private/src/main/java/org/keycloak/broker/provider/util/SimpleHttp.java#L270-L307

Looks like when reading the response body, it tries to use the content-type header from the response. Possibly this is not set by BankID which would then fallback to the system default.

Simplest solution to this would be to switch to use the Apache HTTP Client library directly (same as SimpleHttp uses) and then hardcode to handle the response as UTF-8.

Contributions are welcomed.

**Comment by ullgren** [comment]
Fixed upstream in https://github.com/keycloak/keycloak/commit/acd4f5f793fb4c9eeaf135b57317fa29bce632f1
