### ISSUE TITLE
After successfull bankid identification bankid4keycloak window still open

### ISSUE THREAD

**Issue by rickardpl** [bankid4keycloak/bankid4keycloak#15]
The user dialogue is opened and email is entered, redirect back to my test spring boot application is done. but the window is still shown.
![bild](https://user-images.githubusercontent.com/16462691/85866922-74414c00-b7c8-11ea-8c84-edfaf304591c.png)
Pressing cancel give NPE since session atribute "authresponse" is null
```
16:15:28,357 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: java.lang.NullPointerException
        at org.keycloak.broker.bankid.BankidEndpoint.canel(BankidEndpoint.java:225)
```

Using springboot request.logout() and trying to access protected resource takes med back to keycloak where I choose to identify using bankid, going through the bankid procedure again and arrive to login page again with error
![bild](https://user-images.githubusercontent.com/16462691/85867884-d8b0db00-b7c9-11ea-93c0-056f64b9c794.png)

And after this bankid does not work.

**Comment by ullgren** [comment]
To me this sounds like two different issues. If you agree could you please split them in separate issues.
If not please clarify how you think they are related.

**Comment by ullgren** [comment]
Just wanted to let you know I've recreated the first issue using the BankID desktop app on Windows 10 using firefox.

Will check to see what we can do to solve this, the problem seems to be that the new page is opened in a second tab.

**Comment by ullgren** [comment]
Closed issue by mistake. Sorry
