### ISSUE TITLE
Invalid enduserip

### ISSUE THREAD

**Issue by andrejohansson** [bankid4keycloak/bankid4keycloak#21]
**Describe the bug**

Hosting keycloak in a docker container on Azure, and when I try to login I get the following error when clicking the bankid login button:

```
ERROR [org.keycloak.broker.bankid.client.SimpleBankidClient] (default task-18) Request to /rp/v5/auth failed with status code 400 and payload {"errorCode":"invalidParameters","details":"Invalid endUserIp"}
```

This seems to be a similar issue as reported on the ActiveLogin repo:
https://github.com/ActiveLogin/ActiveLogin.Authentication/issues/213

If I run keycloak locally outside a docker image on Windows I seem to be getting one step longer (the login form is shown).

Is there any setting that might help or is this a bug that needs to be addressed?

**Environment:**
 - OS: linux (keycloak docker)
 - Browser firefox
 - Keycloak version: 15
 - Version of BankID 4 Keycloak: 1.0.0-SNAPSHOT

**Comment by andrejohansson** [comment]
Azure apparently expostes the ip in the header `X-Client-Ip` so adding the following code to the doLogin method of BankidEndpoint seems to work for me:

```java
String ipAddress = request.getHeader("X-Client-IP");
if (ipAddress == null) {
	ipAddress = request.getRemoteAddr();
}

authResponse = bankidClient.sendAuth(nin, ipAddress);
request.getSession().setAttribute("bankid.authresponse", authResponse);
```

**Comment by qvicksilver** [comment]
Getting the correct client ip address behind a reverse proxy is covered in the Keycloak documentation: https://www.keycloak.org/docs/latest/server_installation/#identifying-client-ip-addresses

If the proxy uses a non standard header I'd start looking to see if it's possible to change that behaviour in the proxy.

**Comment by andrejohansson** [comment]
Thanks for pointing out that section, I can´t however find any information about me being able to specify the header name to forward, it´s always the standard `X-Forwarded-*` ones.

So in this case it doesn´t help me on Azure because:

- The loadbalancer is managed by Microsoft, not us (it´s in their infrastructure for Azure containerized apps if you do not choose "bigger" instances of the service or add a custom loadbalancer)
- `X-Forwarded-For` on Azure exists, but it returns ip+port, in contradiction to that it should only return ip according to [mdn documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)
- `X-Client-Ip` only contains the ip but is a non standard header

The hack above worked for our case, it could have been exchange to code that splits out the ip part if it finds an ip:port combo in the header too.

Leaving the notes here and closing since this is really an issue with Azure not conforming to standards.
