### ISSUE TITLE
Keycloak 17

### ISSUE THREAD

**Issue by xperjon** [bankid4keycloak/bankid4keycloak#24]
Any plans of migrating the code to keycloak 17?

**Comment by qvicksilver** [comment]
AFAIK no-one is actively working on it but it may eventually happen. In the meantime contributions are always welcome ;)

**Comment by xperjon** [comment]
Thanxs for reply @qvicksilver!
I tried to build and run the code (as is) with Keycloack 17.0 but stumbled on a problem. Seems that injecting @Context HttpServletRequest is not possible with Quarkus and I don't seem to find a way to get hold of a http session at all. Anyone having similar problems?

**Comment by ullgren** [comment]
Will jump directly to 20.0.x, see #30
