### ISSUE TITLE
Keycloak 15.1.1 HttpServletRequest.HttpSession will not retain attributes

### ISSUE THREAD

**Issue by rickardpl** [bankid4keycloak/bankid4keycloak#26]
Have not been able to get this IDP to work correctly past keycloak-11.0.3. 

While debugging the HttpServletRequest.HttpSession attribute 'bankid.state' is not propagated from /start to /login always resulting in 'unknown error (hint RFA22).

The start endpoint loads the freemarket template, but in the following endpoint there is no attributes at all on the CDI injected HttpSession.

Have you really run this IDP successfully in keycloak-15.1.1?  Or has there been a paradigm shift internally where there are specific SPI objects already present that are meant to be used?

**Comment by rickardpl** [comment]
Tested unsuccessfully on wildfly versions 13.0.1, 15.0.2, 15.1.1, 17.0.1, 18.0.2

**Comment by ullgren** [comment]
Project now uses Keycloak 20.x
