### ISSUE TITLE
Deprecation warning ?

### ISSUE THREAD

**Issue by isrjo** [bankid4keycloak/bankid4keycloak#9]
Following message is printed to the log when starting keycloak.

```[org.jboss.as.dependency.private] (MSC service thread 1-8) WFLYSRV0018: Deployment "deployment.bankid4keycloak-1.0.0-SNAPSHOT.jar" is using a private module ("org.keycloak.keycloak-server-spi-private") which may be changed or removed in future versions without notice.```

**Comment by ullgren** [comment]
Unfortunatly we need to use the keycloak-server-spi-private module since it is the one that holds the IdentityProvider SPI.
